const hero=document.querySelector('.hero'),header=document.querySelector('.site-header'),floating=document.getElementById('floating');
function updateContact(){header.classList.toggle('scrolled',window.scrollY>40);const past=hero.getBoundingClientRect().bottom<=header.getBoundingClientRect().bottom;floating.hidden=!past;floating.classList.toggle('show',past);}
window.addEventListener('scroll',updateContact,{passive:true});window.addEventListener('resize',updateContact);window.addEventListener('pageshow',updateContact);updateContact();
const menu=document.querySelector('.menu-toggle'),nav=document.getElementById('nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');}));
const background=document.getElementById('hero-video'),toggle=document.getElementById('hero-toggle');function syncVideo(){toggle.textContent=background.paused?'Play video':'Pause video';toggle.setAttribute('aria-label',background.paused?'Play background video':'Pause background video');}toggle.addEventListener('click',()=>{if(background.paused)background.play().catch(()=>{});else background.pause();});background.addEventListener('play',syncVideo);background.addEventListener('pause',syncVideo);if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){background.pause();syncVideo();}
const players=Array.from(document.querySelectorAll('.work-video'));players.forEach(v=>v.addEventListener('play',()=>{players.forEach(other=>{if(other!==v)other.pause();});}));
document.getElementById('wa-form').addEventListener('submit',function(e){e.preventDefault();if(!this.reportValidity())return;const f=new FormData(this);const message="Hi Coast to Coast, I'd like a free cleaning quote.\n\nName: "+f.get('name').trim()+"\nService: "+f.get('service')+"\nTown/Postcode: "+f.get('area').trim()+"\nDetails: "+f.get('details').trim();window.open('https://wa.me/447384168302?text='+encodeURIComponent(message),'_blank','noopener');});

const dialogs=Array.from(document.querySelectorAll('.video-dialog'));let returnFocus=null;document.querySelectorAll('.video-launch').forEach(button=>button.addEventListener('click',()=>{const dialog=document.getElementById(button.dataset.dialog);returnFocus=button;dialog.showModal();document.body.classList.add('video-open');dialog.querySelector('video').play().catch(()=>{});}));dialogs.forEach(dialog=>{const close=()=>dialog.close();dialog.querySelector('.dialog-close').addEventListener('click',close);dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}});dialog.addEventListener('close',()=>{dialog.querySelector('video').pause();document.body.classList.remove('video-open');if(returnFocus)returnFocus.focus();});});
